### ISSUE TITLE
Retrieval Augmented Generation (RAG) for PDF files

### ISSUE THREAD

**Issue by softpedia-inc** [Vali-98/ChatterUI#63] opened 2024-08-11 15:28 UTC
Dear developers,
When can the users of ChatterUI expect to have the Retrieval Augmented Generation (RAG) feature with PDF files being fully supported?

**Comment by Vali-98** [comment] 2024-08-12 13:19
Duplicate of #41

**Closed by Vali-98** 2024-08-12 13:19 UTC
