### ISSUE TITLE
Continue generation is broken

### ISSUE THREAD

**Issue by GameOverFlowChart** [Vali-98/ChatterUI#52] opened 2024-07-28 22:18 UTC
I don't know since how many versions that's the case but if you edit an output and let the model continue the output, the gui will glitch and deleting everything in that message that was from before the continuation.

**Comment by Vali-98** [comment] 2024-07-28 23:59
Could you explain further? I cannot replicate this behavior.

**Comment by GameOverFlowChart** [comment] 2024-07-29 07:28
I try to attach an image. Look how it changes in the end so that only the new generated text is shown and the part which I edited is lost.


![Droid_29072024092512](https://github.com/user-attachments/assets/06b0749b-c86c-42b5-a7fb-9163547170ed)

**Comment by GameOverFlowChart** [comment] 2024-07-29 07:34
It's the ⏩ button I used in case that it's not clear.

**Comment by Vali-98** [comment] 2024-07-29 13:32
Yes, this seems to be reproducable on my side, I will look into it when I have the time, thanks for the report.

**Comment by Vali-98** [comment] 2024-07-29 15:03
Fixed in f5edb30

**Closed by Vali-98** 2024-07-29 15:03 UTC
Labels: bug
